version: '3.8'

services:
  openwebrx:
    # Using an image variant that features extensive HackRF driver integrations
    image: slechev/openwebrxplus:latest
    container_name: openwebrx
    restart: always
    network_mode: host
    # Grant full device manipulation capabilities to bypass Raspberry Pi USB locking
    privileged: true
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    volumes:
      - ./openwebrx_data:/var/lib/openwebrx
